### ISSUE TITLE
Crash on save

### ISSUE THREAD

**Issue by willco007** [idmean/CodaLess#3]
We are seeing a crash on save in your plugin, here is the offending code stack.  Please fix this and re-submit a new version, thanks.

`Application Specific Information:
Performing @selector(ok:) from sender NSButton 0x6000003414a0
fatal error: unexpectedly found nil while unwrapping an Optional value

Thread 0:: Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	0x000000010f061610 _TFSs18_fatalErrorMessageFTVSs12StaticStringS_S_Su_T_ + 160
1   at.zujab.CodaLess             	0x000000010f00bd82 _TFC8CodaLess8CodaLess16textViewWillSavefS0_FGSQCSo12CodaTextView_T_ + 1250
2   at.zujab.CodaLess             	0x000000010f00dff6 _TToFC8CodaLess8CodaLess16textViewWillSavefS0_FGSQCSo12CodaTextView_T_ + 54
3   com.panic.Coda2               	0x00000001074d1912 -[PlugInManager notifyPluginsWithSelector:document:] + 341
4   com.panic.Coda2               	0x00000001074599af -[CodaDocument saveToURL:ofType:forSaveOperation:completionHandler:] + 76`

**Comment by idmean** [comment]
Fixed an submitted.

**Comment by idmean** [comment]
The plugin seems to be approved but it does not appear on your plugin page. Any reason for that?
