### ISSUE TITLE
Launch path inaccessible exception

### ISSUE THREAD

**Issue by willco007** [idmean/CodaLess#4]
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'

Last Exception Backtrace:
0   CoreFoundation                       0x00007fff8ec75654 __exceptionPreprocess + 148
1   libobjc.A.dylib                      0x00007fff8c16f76e objc_exception_throw + 42
2   CoreFoundation                       0x00007fff8ec75209 -[NSException raise] + 8
3   ExceptionHandling                    0x00007fff86c73aef NSExceptionHandlerExceptionRaiser + 195
4   libobjc.A.dylib                      0x00007fff8c16f76e objc_exception_throw + 42
5   CoreFoundation                       0x00007fff8ec7551d +[NSException raise:format:] + 204
6   Foundation                           0x00007fff8b3ae6ac -[NSConcreteTask launchWithDictionary:] + 443
7   CodaLess                             0x000000010a258438 _TFFC8CodaLess34CodaLessPrefrencesWindowController13windowDidLoadFS0_FT_T_U_FT_T_ + 936
8   libdispatch.dylib                    0x00007fff886f2323 _dispatch_call_block_and_release + 11
9   libdispatch.dylib                    0x00007fff886edc13 _dispatch_client_callout + 7
10  libdispatch.dylib                    0x00007fff886f088f _dispatch_root_queue_drain + 934
11  libdispatch.dylib                    0x00007fff886fefe4 _dispatch_worker_thread3 + 90
12  libsystem_pthread.dylib              0x00007fff8e1aa637 _pthread_wqthread + 728
13  libsystem_pthread.dylib              0x00007fff8e1a840d start_wqthread + 12

**Comment by willco007** [comment]
I'm unsure what version the user is running, but please verify the tool existence check is in place before attempting to launch it.

**Comment by idmean** [comment]
Sorry for bothering you all the time. Fixed an resubmitted.

Is there any reason the plugin does no longer appear in your list?
