### ISSUE TITLE
Remote files possible?

### ISSUE THREAD

**Issue by mrJakez** [idmean/CodaLess#5]
Hi,

I found your plugin and like the idea that coda will be responsible to compile the less files itself. Currently a lot of my projects are remote only, but there seems to be an issue with these kind of less files. 

As far as I can see this fix https://github.com/idmean/CodaLess/issues/1 skips the compiling of the remote less files.

Is there any chance to get this working? I mean compile the file locally on my Mac and automatically upload it to the specific directory on the remote host.

Or do I miss something?

Cheers
Dennis

**Comment by idmean** [comment]
Hi,

at the moment the Coda API offers basically no interface to control uploading or download from/to a remote server and allows you only to retrieve the URL of the remote server. This means the only way to achieve compiling remote files would be to integrate the up/downloading directly into CodaLess – obviously not a good idea.

So no, sorry, this won’t work in the near future, but...
Why do you actually need this? Are you working on files on a remote server? This often indicates a mistake in the development process. 

Cheers
idmean
